version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./assets:/app/assets
      - ./generated_images:/app/generated_images
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped 